import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#0d150e",
        "surface-dim": "#0d150e",
        "surface-bright": "#333b33",
        "surface-container-lowest": "#081009",
        "surface-container-low": "#151d16",
        "surface-container": "#19221a",
        "surface-container-high": "#242c24",
        "surface-container-highest": "#2e372f",
        "on-surface": "#dce5d9",
        "on-surface-variant": "#becab9",
        "inverse-surface": "#dce5d9",
        "inverse-on-surface": "#2a322b",
        outline: "#899484",
        "outline-variant": "#3f4a3c",
        "surface-tint": "#78dc77",
        primary: "#78dc77",
        "on-primary": "#00390a",
        "primary-container": "#4bae4f",
        "on-primary-container": "#003b0b",
        "inverse-primary": "#006e1c",
        secondary: "#e1c560",
        "on-secondary": "#3b2f00",
        "secondary-container": "#7a6400",
        "on-secondary-container": "#ffe383",
        tertiary: "#acd0ab",
        "on-tertiary": "#18371d",
        "tertiary-container": "#81a381",
        "on-tertiary-container": "#1a391e",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#94f990",
        "primary-fixed-dim": "#78dc77",
        "on-primary-fixed": "#002204",
        "on-primary-fixed-variant": "#005313",
        "secondary-fixed": "#ffe179",
        "secondary-fixed-dim": "#e1c560",
        "on-secondary-fixed": "#231b00",
        "on-secondary-fixed-variant": "#554500",
        "tertiary-fixed": "#c7ecc6",
        "tertiary-fixed-dim": "#acd0ab",
        "on-tertiary-fixed": "#022109",
        "on-tertiary-fixed-variant": "#2f4e32",
        background: "#0d150e",
        "on-background": "#dce5d9",
        "surface-variant": "#2e372f",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "max-width": "1200px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        quicksand: ["Quicksand", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "600" },
        ],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-xl": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      maxWidth: {
        content: "1200px",
      },
    },
  },
  plugins: [],
};

export default config;
