/**
 * @fileoverview GET /api/trivia — Dynamic AI-generated eco-trivia endpoint.
 *
 * Uses Groq (llama-3.3-70b) to generate 5 fresh sustainability trivia questions.
 * Implements a 10-minute TTL cache via the shared cache utility to maximise efficiency.
 *
 * @module trivia/route
 */
import { NextResponse } from "next/server";
import { fetchGroq } from "@/utils/ai";
import { isCacheValid, createCacheEntry, CacheEntry } from "@/utils/cache";

/**
 * Represents a single eco-trivia question object generated by the AI.
 */
export interface TriviaQuestion {
  id: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

let cache: CacheEntry<TriviaQuestion[]> | null = null;

/**
 * Strict system prompt defining the persona and output schema for the Groq LLM.
 * Guarantees a perfectly structured JSON array of trivia questions.
 */
const SYSTEM_PROMPT = `Return a JSON array of exactly 5 objects. No markdown, no explanation — raw JSON only.
Generate 5 unique, interesting, and surprising trivia questions about sustainability, climate change, carbon footprints, or eco-friendly habits.
Each object must match this schema:
{"id":"unique_slug","question":"The question text?","options":["Option A","Option B","Option C","Option D"],"correctIndex":integer_0_to_3,"explanation":"1-2 sentences explaining the correct answer with an interesting fact."}`;

/**
 * Calls the central Groq utility to generate 5 fresh, random eco-trivia questions.
 *
 * @returns A Promise resolving to an array of strictly-typed TriviaQuestion objects.
 */
async function generateTrivia(): Promise<TriviaQuestion[]> {
  return fetchGroq<TriviaQuestion[]>(
    SYSTEM_PROMPT,
    "Generate 5 new random eco-trivia questions. Make sure they are different from standard common knowledge."
  );
}

/**
 * API Route Handler for GET /api/trivia.
 * Fetches dynamic AI-generated trivia and employs a 10-minute cache mechanism
 * to heavily optimize efficiency and prevent API rate-limiting.
 *
 * @param request - The incoming HTTP GET request.
 * @returns A NextResponse containing the array of fully formed TriviaQuestions.
 */
export async function GET(request: Request): Promise<NextResponse> {
  const url = new URL(request.url);
  const forceRefresh = url.searchParams.get("refresh") === "1";

  if (!forceRefresh && isCacheValid(cache)) {
    return NextResponse.json(cache.data, { status: 200 });
  }

  try {
    const questions = await generateTrivia();
    cache = createCacheEntry(questions, 600_000);
    return NextResponse.json(questions, { status: 200 });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error("[trivia] API error:", message);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
